#!/bin/bash

set -e

mkdir lessons

mkdir lessons/1-three-stage-thinking
pushd lessons/1-three-stage-thinking
git init
git commit --allow-empty -m 'Initial commit'
cat >index.html <<EOL
<html>
    <head>
        <title>My First Git Repository</title>
        <style type="text/css">
            body { background-color: pink }
        </style>
    </head>
    <body>
        <h1>My First Git Repository</h1>
        <p>My name is Peter Lundgren</p>
    </body>
</html>
EOL
cat >README.md <<EOL
Lesson 1: Three Stage Thinking
==============================

1.  Change index.html to include your name.
2.  Change the background color to your favorite color.
3.  Study the output of \`git status\` and \`git diff\`
4.  Stage the file with \`git add index.html\`
5.  Study the output of \`git status\`, \`git diff\` and \`git diff --staged\`
6.  Maybe we should split this into two commits. Unstage index.html by
    following the advice from \`git status\`.
7.  Stage your name change first with \`git add -p\` and commit the change.
8.  Next, stage and commit the background-color change. This time use
    \`git commit --verbose\`. Note that the commit message prompt shows you the
    diff of what you are about to commit.
9.  Study the output of \`git log\`, \`git lol\`, \`git log -p\`, and
    \`git log --stat\`.
EOL
git add index.html README.md
git commit -m 'Add amazing webpage'
popd

mkdir lessons/2-branching-and-merging
pushd lessons/2-branching-and-merging
git init
git commit --allow-empty -m 'Initial commit'
cat >index.html <<EOL
<html>
    <head>
        <title>My First Git Repository</title>
        <style type="text/css">
            body { background-color: pink }
        </style>
    </head>
    <body>
        <h1>My First Git Repository</h1>
        <p>My name is Peter Lundgren</p>
    </body>
</html>
EOL
cat >README.md <<EOL
Lesson 2: Branching and Merging
===============================

We return to our simple web page. This time, we will make the same two changes
as last time (changing the name and background color), but we will commit each
change on a separate branch and then merge them back into master.

1.  Create a branch called \`feature/change-name\` and checkout that branch
    with \`git checkout -b feature/change-name\` (equivalent to
    \`git branch feature/change-name\` followed by
    \`git checkout feature/change-name\`).
2.  Study the output of \`git branch\`
3.  Change index.html to include your name.
4.  Add and commit your change.
5.  Study the output of \`git lol\`. \`git lol\` is an alias you configured
    before class. View your aliases with \`git config --list | grep alias\`.
6.  Return to master with \`git checkout master\`.
7.  Create and checkout a branch called \`feature/change-background\`.
8.  Study the output of \`git lol\`, and \`git lola\`. What's the difference
    between the two?
9.  Change the background color to your favorite color.
10. Add and commit your change.
11. Study the output of \`git lol\`, \`git lola\`,
    \`git log -p feature/change-name --not master\`, and
    \`git log -p feature/change-background --not master\`.
12. Return to master with \`git checkout master\`.
13. Merge the \`feature/change-name\` branch into master.
14. Study the output of \`git lol\`, \`git lola\`,
    \`git log -p feature/change-name --not master\`, and
    \`git log -p feature/change-background --not master\`.
15. Merge the \`feature/change-background\` branch into master.
16. Study the output of \`git lol\`, \`git lola\`,
    \`git log -p feature/change-name --not master\`, and
    \`git log -p feature/change-background --not master\`.
EOL
git add index.html README.md
git commit -m 'Add amazing webpage'
popd

mkdir lessons/3-tags
pushd lessons/3-tags
git init
git commit --allow-empty -m 'Initial commit'
cat >README.md <<EOL
Lesson 3: Tags
==============

There are two different kinds of tags in git: lightweight and annotated tags.
Lightweight tags are similar to branches. They are simple named pointers. The
difference is that they aren't allowed to change once they are created.
Annotated tags are more similar to commits in that they also contain an author,
timestamp, and message.

1.  Create a new tag called foo pointing to the same commit that HEAD is
    pointing to by running git tag <tagname>.
2.  Study the output of \`git lol\`.
3.  Create an annotated tag called bar pointing to the commit that added a.txt.
    Use some of the \`git log\` commands you've learned to find the correct
    commit. Use \`git help tag\` to find the correct arguments to \`git tag\`.
4.  How do \`git show foo\` and \`git show bar\` differ because bar in an
    annotated tag?
EOL
git add README.md
git commit -m 'Lesson 3'
cat >a.txt <<EOL
 AA
A  A
AAAA
A  A
A  A
EOL
git add a.txt
git commit -m 'Add a.txt'
cat >b.txt <<EOL
BBB
B  B
BBB
B  B
BBB
EOL
git add b.txt
git commit -m 'Add b.txt'
popd

mkdir lessons/4-rebase
pushd lessons/4-rebase
git init
git commit --allow-empty -m 'Initial commit'
cat >README.md <<EOL
Lesson 4: Rebase
================

The history of this repository currently looks like this:

         E---F---G feature/bar
        /
    ---A---B master
        \\
         C---D feature/foo

The goal of this lesson is to use \`git rebase\` to replay the history so that
it looks like this:

    ---A---B---C---D---E---F---G master

Consult \`git help rebase\` if you need help.

When you're done, \`git lola\` should look like the following (your hashes will
be different).

    * 5055df0 (HEAD, master) Add g.txt
    * fe5b473 Add f.txt
    * 023cfb4 Add e.txt
    * c8c41c8 Add d.txt
    * 9587aa7 Add c.txt
    * 3c48f2c Add b.txt
    * 5966c58 Add a.txt
    * 590dbaf Lesson 4
    * a869b2d Initial commit
EOL
git add README.md
git commit -m 'Lesson 4'
cat >a.txt <<EOL
 AA
A  A
AAAA
A  A
A  A
EOL
git add a.txt
git commit -m 'Add a.txt'
cat >b.txt <<EOL
BBB
B  B
BBB
B  B
BBB
EOL
git add b.txt
git commit -m 'Add b.txt'
git checkout -b feature/foo HEAD~1
cat >c.txt <<EOL
 CCC
C
C
C
 CCC
EOL
git add c.txt
git commit -m 'Add c.txt'
cat >d.txt <<EOL
DDD
D  D
D  D
D  D
DDD
EOL
git add d.txt
git commit -m 'Add d.txt'
git checkout -b feature/bar HEAD~2
cat >e.txt <<EOL
EEEE
E
EEE
E
EEEE
EOL
git add e.txt
git commit -m 'Add e.txt'
cat >f.txt <<EOL
FFFF
F
FFF
F
F
EOL
git add f.txt
git commit -m 'Add f.txt'
cat >g.txt <<EOL
 GGG
G
G GG
G  G
 GGG
EOL
git add g.txt
git commit -m 'Add g.txt'
git checkout master
popd

mkdir lessons/5-interactive-rebase
pushd lessons/5-interactive-rebase
git init
git commit --allow-empty -m 'Initial commit'
cat >README.md <<EOL
Lesson 5: Interactive Rebase
============================

The master branch currently has 5 files: a.txt, b.txt, c.txt, d.txt, and e.txt
(plus this README.md). Their contents are correct, but the development process
to get them here was a bit messy. Your goal is to clean up the history so that
it looks like the following (your sha1sums will be different):

    $ git lol
    * 30854df (HEAD -> master) Add e.txt
    * 8b08559 Add d.txt
    * 9e156c8 Add c.txt
    * d1dd11c Add b.txt
    * 2ecdcf3 Add a.txt
    * c60e835 Lesson 5
    * dd52767 Initial commit

You have three different tasks to complete:

1.  Squash the two commits working on d.txt together.
2.  Split up the commit adding both a.txt and b.txt.
3.  Reorder the commits so that they are in the order a, b, c, d, e.

I recommend concentrating on one task at a time. Before each rebase, drop a
branch with \`git branch <branchname>\`. That way, you can easily return to a
previous step with \`git reset --hard <branchname>\` if you make a mistake.
EOL
git add README.md
git commit -m 'Lesson 5'
cat >c.txt <<EOL
 CCC
C
C
C
 CCC
EOL
git add c.txt
git commit -m 'Add c.txt'
cat >a.txt <<EOL
 AA
A  A
AAAA
A  A
A  A
EOL
git add a.txt
cat >b.txt <<EOL
BBB
B  B
BBB
B  B
BBB
EOL
git add b.txt
git commit -m 'Add a.txt and b.txt'
cat >d.txt <<EOL
ddd
d  d
d  d
d  d
ddd
EOL
git add d.txt
git commit -m 'Add d.txt'
cat >e.txt <<EOL
EEEE
E
EEE
E
EEEE
EOL
git add e.txt
git commit -m 'Add e.txt'
cat >d.txt <<EOL
DDD
D  D
D  D
D  D
DDD
EOL
git add d.txt
git commit -m 'Capitalize D'
popd
