#!/bin/bash

set -e

mkdir demos

mkdir demos/1-git-help

mkdir demos/2-git-init

mkdir demos/3-three-stage-thinking
pushd demos/3-three-stage-thinking
git init
git commit --allow-empty -m 'Initial commit'
cat >hello.c <<EOL
int main(void)
{
    printf("Hello World\n");
    return 0;
}
EOL
git add hello.c
git commit -m 'Add hello'
popd

mkdir demos/4-trees-hashes-blobs
pushd demos/4-trees-hashes-blobs
git init
cat >hello.c <<EOL
#include <stdio.h>

int main(void)
{
    printf("Hello World\n");
    return 0;
}
EOL
popd

mkdir demos/5-interactive-rebase
pushd demos/5-interactive-rebase
git init
git commit --allow-empty -m 'Initial commit'
cat >a.txt <<EOL
 AA
A  A
AAAA
A  A
A  A
EOL
git add a.txt
git commit -m 'Add a.txt'
cat >b.txt <<EOL
BBB
B  B
BBB
B  B
BBB
EOL
git add b.txt
git commit -m 'Add b.txt'
cat >c.txt <<EOL
 CCC
C
C
C
 CCC
EOL
git add c.txt
git commit -m 'Add c.txt'
cat >d.txt <<EOL
DDD
D  D
D  D
D  D
DDD
EOL
git add d.txt
git commit -m 'Add d.txt'
cat >e.txt <<EOL
EEEE
E
EEE
E
EEEE
EOL
git add e.txt
git commit -m 'Add e.txt'
cat >f.txt <<EOL
FFFF
F
FFF
F
F
EOL
git add f.txt
git commit -m 'Add f.txt'
cat >g.txt <<EOL
 GGG
G
G GG
G  G
 GGG
EOL
git add g.txt
git commit -m 'Add g.txt'
popd

mkdir demos/6-stash
pushd demos/6-stash
git init
git commit --allow-empty -m 'Initial commit'
cat >hello.c <<EOL
int main(void)
{
    printf("Hello World\n");
    return 0;
}
EOL
git add hello.c
git commit -m 'Add hello'
git checkout -b foo
cat >hello.c <<EOL
#include <stdio.h>

int main(void)
{
    printf("Hello World\n");
    return 0;
}
EOL
git add hello.c
git commit -m 'Include stdio'
git checkout -b bar HEAD~1
cat >hello.c <<EOL
int main(void)
{
    printf("Hello Class\n");
    return 0;
}
EOL
git add hello.c
git commit -m 'Hello Class'
git checkout master
cat >hello.c <<EOL
int main(void)
{
    printf("Hello World\n");
    return 0;
}
/* Unstaged modifications */
EOL
popd

mkdir demos/7-submodules
pushd demos/7-submodules
mkdir tmp
mkdir tmp/color
pushd tmp/color
git init
git commit --allow-empty -m 'Initial commit'
cat >color.h <<EOL
void color_start(void);
void color_end(void);
EOL
cat >color.c <<EOL
#include <stdio.h>

#define RED   "\x1B[31m"
#define GRN   "\x1B[32m"
#define YEL   "\x1B[33m"
#define BLU   "\x1B[34m"
#define MAG   "\x1B[35m"
#define CYN   "\x1B[36m"
#define WHT   "\x1B[37m"
#define RESET "\x1B[0m"

void color_start(void)
{
    printf(RED);
}

void color_end(void)
{
    printf(RESET);
}
EOL
git add color.h color.c
git commit -m 'Color module'
popd
mkdir tmp/greeting
pushd tmp/greeting
git init
git commit --allow-empty -m 'Initial commit'
cat >greeting.h <<EOL
void greeting(void);
EOL
cat >greeting.c <<EOL
#include <stdio.h>

void greeting(void)
{
    printf("Hello World\n");
}
EOL
git add greeting.h greeting.c
git commit -m 'Greeting module'
popd
mkdir tmp/hello
pushd tmp/hello
git init
git commit --allow-empty -m 'Initial commit'
cat >.gitignore <<EOL
hello
EOL
cat >Makefile <<EOL
all:
	gcc -o hello hello.c color/color.c greeting/greeting.c
EOL
cat >hello.c <<EOL
#include "color/color.h"
#include "greeting/greeting.h"

int main(void)
{
    color_start();
    greeting();
    color_end();
    return 0;
}
EOL
git add .gitignore Makefile hello.c
git commit -m 'Hello super-project'
popd
mkdir remotes
pushd remotes
git clone --bare `readlink -f ../tmp/color`
git clone --bare `readlink -f ../tmp/greeting`
git clone --bare `readlink -f ../tmp/hello`
popd
rm -rf tmp
popd
