#!/bin/bash

set -e

mkdir demos

mkdir demos/1-git-help

mkdir demos/2-git-init

mkdir demos/3-three-stage-thinking
pushd demos/3-three-stage-thinking
git init
git commit --allow-empty -m 'Initial commit'
cat >hello.c <<EOL
int main(void)
{
    printf("Hello World\n");
    return 0;
}
EOL
git add hello.c
git commit -m 'Add hello'
popd

mkdir demos/4-trees-hashes-blobs
pushd demos/4-trees-hashes-blobs
git init
cat >hello.c <<EOL
#include <stdio.h>

int main(void)
{
    printf("Hello World\n");
    return 0;
}
EOL
popd
